---
- name: Installing s/w applications
  hosts: all
  tasks:
    - name: Installing multiple software applications
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
      with_items:
        - tree
        - git
        - maven

...
