- name: create user using host scope varibles
  hosts: 172.31.26.191
  tasks:
   - name: create user
     user:
      name: "{{a}}"
      password: "{{b}}"
      uid: "{{c}}"
      home: "{{d}}"
      shell: "{{e}}"
...
